Max games in ticket
thales-markets/contracts-v2 pull request #67
Opened 2024-06-21 15:05 UTC by kirilaa

2024-06-22 09:02 UTC, vladanthales requested changes

2024-06-22 09:02 UTC, vladanthales commented on contracts/core/AMM/SportsAMMV2RiskManager.sol
> +        uint _maxTicketSize
Rename it to `_ticketSize`.

2024-06-22 09:02 UTC, vladanthales commented on contracts/interfaces/ISportsAMMV2RiskManager.sol
> +        uint _maxTicketSize
Rename it to `_ticketSize`.

2024-06-24 05:34 UTC, vladanthales approved these changes

2024-07-02 11:40 UTC, grujawork approved these changes

2024-07-02 12:58 UTC, danijelthales approved these changes

2024-07-02 12:59 UTC, vladanthales approved these changes

2024-07-02 13:00 UTC, merged